// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// ConfirmModal is a generic confirmation dialog driven by Alpine store "confirm".
// From any Alpine component, open it with:
//
//	$store.confirm.open({
//	  title: 'Delete scenario?',
//	  message: 'This cannot be undone.',
//	  confirmLabel: 'Delete',
//	  confirmClass: 'btn-error',
//	  onConfirm: () => this.deleteScenario()
//	})
//
// Register the store in your layout (before Alpine loads) with:
//
//	document.addEventListener('alpine:init', () => {
//	  Alpine.store('confirm', {
//	    show: false, title: '', message: '',
//	    confirmLabel: 'Confirm', cancelLabel: 'Cancel', confirmClass: 'btn-primary',
//	    onConfirm: null,
//	    open(opts) {
//	      this.title = opts.title ?? 'Confirm';
//	      this.message = opts.message ?? '';
//	      this.confirmLabel = opts.confirmLabel ?? 'Confirm';
//	      this.cancelLabel = opts.cancelLabel ?? 'Cancel';
//	      this.confirmClass = opts.confirmClass ?? 'btn-primary';
//	      this.onConfirm = typeof opts.onConfirm === 'function' ? opts.onConfirm : () => {};
//	      this.show = true;
//	    },
//	    close() { this.show = false; },
//	    async runConfirm() {
//	      if (this.onConfirm) await Promise.resolve(this.onConfirm());
//	      this.close();
//	    }
//	  });
//	});
//
//go:generate templ
func ConfirmModal() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog id=\"confirmModal\" class=\"modal modal-bottom sm:modal-middle\" x-data x-effect=\"$store.confirm.show ? $el.showModal() : $el.close()\" @close=\"$store.confirm.show = false\" @cancel.prevent=\"$store.confirm.close()\"><div class=\"modal-box\"><h3 class=\"font-bold text-lg\" x-text=\"$store.confirm.title\"></h3><p class=\"py-2 text-base-content/80\" x-text=\"$store.confirm.message\"></p><div class=\"modal-action\"><button type=\"button\" class=\"btn btn-ghost\" @click=\"$store.confirm.close()\" x-text=\"$store.confirm.cancelLabel\"></button> <button type=\"button\" class=\"btn\" :class=\"$store.confirm.confirmClass\" @click=\"$store.confirm.runConfirm()\" x-text=\"$store.confirm.confirmLabel\"></button></div></div><form method=\"dialog\" class=\"modal-backdrop\"><button type=\"button\">close</button></form></dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
