// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"fmt"
	"github.com/aaronlee232/redis-gui-tester/internal/models"
)

//go:generate templ

// StatusIcon returns the appropriate icon for a scenario status
// TODO: Status field needs to be added to Scenario model
func getStatusIcon(status models.ScenarioStatus) string {
	switch status {
	case models.StatusPassed:
		return "✓"
	case models.StatusFailed:
		return "✗"
	default:
		return "−"
	}
}

func getStatusColor(status models.ScenarioStatus) string {
	switch status {
	case models.StatusPassed:
		return "text-success"
	case models.StatusFailed:
		return "text-error"
	default:
		return "text-base-content/40"
	}
}

// The individual item (Accordion)
func ScenarioItem(s *models.Scenario) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"collapse collapse-plus border border-base-300 bg-base-100 rounded-lg\" x-data=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("scenarioItem(%d)", s.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 36, Col: 129}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><input type=\"checkbox\" class=\"peer\"><div class=\"collapse-title flex items-center gap-4 font-semibold text-base peer-checked:bg-base-200 transition-colors peer-checked:font-bold\"><!-- Status Icon -->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 = []any{"text-xl shrink-0", getStatusColor(s.Status)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var3...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<span class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var3).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var5 string
		templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(getStatusIcon(s.Status))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 41, Col: 29}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</span><!-- Scenario Title --><span class=\"grow\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 string
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(s.Title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 44, Col: 31}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</span></div><div class=\"collapse-content pt-4\"><div class=\"divider my-0\"></div><!-- Two-column layout --><div class=\"flex w-full\"><!-- Left Column --><div class=\"flex-1 flex flex-col space-y-4\"><!-- Description Section --><div><label class=\"label pb-2\"><span class=\"label-text font-semibold\">Description</span></label><p class=\"text-sm text-base-content/80 leading-relaxed\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var7 string
		templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(s.Description)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 57, Col: 77}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p></div><!-- Commands Section --><div><label class=\"label pb-2\"><span class=\"label-text font-semibold\">Commands</span></label><div class=\"bg-base-900 text-base-100 p-3 rounded-lg text-xs overflow-x-auto border border-base-300 font-mono\"><code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, cmd := range s.Commands {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "<div class=\"py-1\"><span class=\"text-base-content/50\">$ redis-cli</span> <span class=\"text-base-content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(cmd)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 69, Col: 47}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</span></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</code></div></div><div class=\"mt-auto flex flex-row gap-2\"><!-- Run Button --><div class=\"grow pt-2\"><button type=\"button\" class=\"min-w-full btn btn-success btn-sm\" @click=\"runScenario()\">Run Scenario</button></div><!-- Edit Button --><div class=\"pt-2\"><button class=\"btn btn-primary btn-sm\" hx-get=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var9 string
		templ_7745c5c3_Var9, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("/api/scenario/form/%d", s.ID))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 84, Col: 59}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var9))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "\" hx-swap=\"innerHTML\" hx-target=\"#saveScenarioModalContainer\" hx-trigger=\"click\">Edit</button></div><!-- Delete Button --><div class=\"pt-2\"><button type=\"button\" class=\"btn btn-error btn-sm\" @click=\"$store.confirm.open({ title: 'Delete scenario?', message: 'This cannot be undone.', confirmLabel: 'Delete', confirmClass: 'btn-error', onConfirm: () => deleteScenario() })\">Delete</button></div></div></div><!-- Vertical Divider --><div class=\"grow-0 divider divider-horizontal\"></div><!-- Right Column (Terminal Output) --><div class=\"flex-1 space-y-4 flex flex-col\"><!-- Redis Responses Terminal --><div class=\"flex-1 flex flex-col\"><label class=\"label pb-2\"><span class=\"label-text font-semibold\">Redis Responses</span></label><div class=\"bg-base-900 text-success p-3 rounded-lg font-mono text-xs overflow-y-auto border border-base-600 flex-1 min-h-32\" hx-target=\"this\"><!-- Terminal content populated via HTMX or command execution --></div></div><!-- Horizontal Divider --><!-- Expected Responses Terminal --><div class=\"flex-1 flex flex-col\"><label class=\"label pb-2\"><span class=\"label-text font-semibold\">Expected Responses</span></label><div class=\"bg-base-900 text-info p-3 rounded-lg font-mono text-xs overflow-y-auto border border-base-600 flex-1 min-h-32\"><code>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, res := range s.ExpectedResponses {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "<div class=\"py-1\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var10 string
			templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(res)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/ui/components/scenario.templ`, Line: 127, Col: 32}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</code></div></div></div></div></div></div><script>\n\tfunction scenarioItem(id) {\n\t\treturn {\n\t\t\tid: id,\n\t\t\tasync deleteScenario() {\n\t\t\t\ttry {\n\t\t\t\t\tconst response = await fetch(\"/api/scenario/delete/\" + this.id, { method: \"DELETE\" });\n\t\t\t\t\tif (response.ok) {\n\t\t\t\t\t\thtmx.trigger(\"#scenario-list\", \"refreshScenarioList\");\n\t\t\t\t\t\tAlpine.store(\"toast\").show(\"Scenario deleted\", \"success\");\n\t\t\t\t\t} else {\n\t\t\t\t\t\tAlpine.store(\"toast\").show(\"Delete failed\", \"error\");\n\t\t\t\t\t}\n\t\t\t\t} catch (error) {\n\t\t\t\t\tconsole.error(\"Error deleting scenario:\", error);\n\t\t\t\t\tAlpine.store(\"toast\").show(\"Delete failed\", \"error\");\n\t\t\t\t}\n\t\t\t},\n\t\t\tasync runScenario() {\n\t\t\t\ttry {\n\t\t\t\t\tconst response = await fetch(\"/api/tester/run-scenario/\" + this.id, { method: \"POST\" });\n\t\t\t\t\tif (response.ok) {\n\t\t\t\t\t\tAlpine.store(\"toast\").show(\"Scenario run completed\", \"success\");\n\t\t\t\t\t} else {\n\t\t\t\t\t\tAlpine.store(\"toast\").show(\"Run failed\", \"error\");\n\t\t\t\t\t}\n\t\t\t\t} catch (error) {\n\t\t\t\t\tconsole.error(\"Error running scenario:\", error);\n\t\t\t\t\tAlpine.store(\"toast\").show(\"Run failed\", \"error\");\n\t\t\t\t}\n\t\t\t},\n\t\t}\n\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// The full list container
func ScenarioList(scenarios []*models.Scenario) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<ul class=\"space-y-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, s := range scenarios {
			templ_7745c5c3_Err = ScenarioItem(s).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</ul>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
